INSERT INTO `currency` (`id`, `name`, `alpha_3`) VALUES
(8, 'Lek', 'ALL'),
(12, 'Dinar algérien', 'DZD'),
(32, 'Peso argentin', 'ARS'),
(36, 'Dollar australien', 'AUD'),
(44, 'Dollar des Bahamas', 'BSD'),
(48, 'Dinar de Bahreïn', 'BHD'),
(50, 'Taka', 'BDT'),
(51, 'Dram arménien', 'AMD'),
(52, 'Dollar de Barbade', 'BBD'),
(60, 'Dollar des Bermudes', 'BMD'),
(64, 'Ngultrum', 'BTN'),
(68, 'Boliviano', 'BOB'),
(72, 'Pula', 'BWP'),
(84, 'Dollar de Belize', 'BZD'),
(90, 'Dollar de Salomon', 'SBD'),
(96, 'Dollar de Brunei', 'BND'),
(104, 'Kyat', 'MMK'),
(108, 'Franc du Burundi', 'BIF'),
(116, 'Riel', 'KHR'),
(124, 'Dollar canadien', 'CAD'),
(132, 'Escudo du Cap-Vert', 'CVE'),
(136, 'Dollar des Iles Caïmanes', 'KYD'),
(144, 'Roupie de Sri Lanka', 'LKR'),
(152, 'Peso chilien', 'CLP'),
(156, 'Yuan Ren-Min-Bi', 'CNY'),
(170, 'Peso colombien', 'COP'),
(174, 'Franc des Comores', 'KMF'),
(188, 'Colon de Costa Rica', 'CRC'),
(191, 'Kuna', 'HRK'),
(192, 'Peso cubain', 'CUP'),
(203, 'Couronne tchèque', 'CZK'),
(208, 'Couronne danoise', 'DKK'),
(214, 'Peso dominicain', 'DOP'),
(222, 'Colon du El Salvador', 'SVC'),
(230, 'Birr éthiopien', 'ETB'),
(232, 'Nakfa', 'ERN'),
(233, 'Couronne estonienne', 'EEK'),
(238, 'Livre de Falkland', 'FKP'),
(242, 'Dollar de Fidji', 'FJD'),
(262, 'Franc de Djibouti', 'DJF'),
(270, 'Dalasi', 'GMD'),
(292, 'Livre de Gibraltar', 'GIP'),
(320, 'Quetzal', 'GTQ'),
(324, 'Franc guinéen', 'GNF'),
(328, 'Dollar de Guyane', 'GYD'),
(332, 'Gourde', 'HTG'),
(340, 'Lempira', 'HNL'),
(344, 'Dollar de Hong-Kong', 'HKD'),
(348, 'Forint', 'HUF'),
(352, 'Couronne islandaise', 'ISK'),
(356, 'Roupie indienne', 'INR'),
(360, 'Rupiah', 'IDR'),
(364, 'Rial iranien', 'IRR'),
(368, 'Dinar iraquien', 'IQD'),
(376, 'Nouvel israëli sheqel', 'ILS'),
(388, 'Dollar jamaïcain', 'JMD'),
(392, 'Yen', 'JPY'),
(398, 'Tenge', 'KZT'),
(400, 'Dinar jordanien', 'JOD'),
(404, 'Shilling du Kenya', 'KES'),
(408, 'Won de la Corée du Nord', 'KPW'),
(410, 'Won', 'KRW'),
(414, 'Dinar koweïtien', 'KWD'),
(417, 'Som', 'KGS'),
(418, 'Kip', 'LAK'),
(422, 'Livre libanaise', 'LBP'),
(426, 'Loti', 'LSL'),
(428, 'Lats letton', 'LVL'),
(430, 'Dollar libérien', 'LRD'),
(434, 'Dinar libyen', 'LYD'),
(440, 'Litas lituanien', 'LTL'),
(446, 'Pataca', 'MOP'),
(454, 'Kwacha de Malawi', 'MWK'),
(458, 'Ringgit de Malaisie', 'MYR'),
(462, 'Rufiyaa', 'MVR'),
(478, 'Ouguija', 'MRO'),
(480, 'Roupie de Maurice', 'MUR'),
(484, 'Peso mexicain', 'MXN'),
(496, 'Tugrik', 'MNT'),
(498, 'Leu de Moldovie', 'MDL'),
(504, 'Dirham marocain', 'MAD'),
(512, 'Rial Omani', 'OMR'),
(516, 'Dollar namibien', 'NAD'),
(524, 'Roupie du Népal', 'NPR'),
(532, 'Florin des Antilles', 'ANG'),
(533, 'Florin d''Aruba', 'AWG'),
(548, 'Vatu', 'VUV'),
(554, 'Dollar néo-zélandais', 'NZD'),
(558, 'Cordoba Oro', 'NIO'),
(566, 'Naira', 'NGN'),
(578, 'Couronne norvégienne', 'NOK'),
(586, 'Roupie du Pakistan', 'PKR'),
(590, 'Balboa', 'PAB'),
(598, 'Kina', 'PGK'),
(600, 'Guarani', 'PYG'),
(604, 'Nouveau Sol', 'PEN'),
(608, 'Peso philippin', 'PHP'),
(634, 'Riyal du Qatar', 'QAR'),
(643, 'Rouble russe', 'RUB'),
(646, 'Franc du Rwanda', 'RWF'),
(654, 'Livre de Sainte-Hélène', 'SHP'),
(678, 'Dobra', 'STD'),
(682, 'Riyal saoudien', 'SAR'),
(690, 'Roupie des Seychelles', 'SCR'),
(694, 'Leone', 'SLL'),
(702, 'Dollar de Singapour', 'SGD'),
(704, 'Dong', 'VND'),
(706, 'Shilling de Somalie', 'SOS'),
(710, 'Rand', 'ZAR'),
(748, 'Lilangeni', 'SZL'),
(752, 'Couronne suédoise', 'SEK'),
(756, 'Franc suisse', 'CHF'),
(760, 'Livre syrienne', 'SYP'),
(764, 'Baht', 'THB'),
(776, 'Pa''anga', 'TOP'),
(780, 'Dollar de la Trinité et de Tobago', 'TTD'),
(784, 'Dirham des émirats arabes unis', 'AED'),
(788, 'Dinar tunisien', 'TND'),
(800, 'Nouveau Shilling ougandais', 'UGX'),
(807, 'Denar', 'MKD'),
(818, 'Livre égyptienne', 'EGP'),
(826, 'Livre Sterling', 'GBP'),
(834, 'Shilling de Tanzanie', 'TZS'),
(840, 'Dollar des États-Unis', 'USD'),
(858, 'Peso Uruguayo', 'UYU'),
(860, 'Soum d''Ouzbékistan', 'UZS'),
(882, 'Tala', 'WST'),
(886, 'Riyal du Yémen', 'YER'),
(894, 'Kwacha de Zambie', 'ZMK'),
(901, 'Nouveau dollar de Taïwan', 'TWD'),
(931, 'Peso Convertible', 'CUC'),
(932, 'Dollar du Zimbabwe', 'ZWL'),
(934, 'Manat', 'TMT'),
(936, 'Ghana Cedi', 'GHS'),
(937, 'Bolivar Fuerte', 'VEF'),
(938, 'Livre soudanaise', 'SDG'),
(940, 'Uruguay Peso en Unidades Indexadas', 'UYI'),
(941, 'Dinar de Serbie', 'RSD'),
(943, 'Metical', 'MZN'),
(944, 'Manat', 'AZN'),
(946, 'Nouveau Leu', 'RON'),
(948, 'WIR Franc', 'CHW'),
(949, 'Nouvelle Livre', 'TRY'),
(950, 'Franc CFA - BEAC  ‡', 'XAF'),
(951, 'Dollar des Caraïbes orientales', 'XCD'),
(952, 'Franc CFA - BCEAO †', 'XOF'),
(953, 'Franc CFP', 'XPF'),
(955, 'Unité européenne composée (EURCO)', 'XBA'),
(956, 'Unité monétaire européenne (U.M.E.-6 monnaie)', 'XBB'),
(957, 'Unité de compte 9 (U.E.C.-9 monnaie)', 'XBC'),
(958, 'Unité de compte 17(U.E.C.-17 monnaie)', 'XBD'),
(959, 'Or', 'XAU'),
(960, 'Droit de tirage spécial (D.T.S.)', 'XDR'),
(961, 'Argent', 'XAG'),
(962, 'Platine', 'XPT'),
(964, 'Palladium', 'XPD'),
(968, 'Dollar de Suriname', 'SRD'),
(969, 'Malagasy Ariary', 'MGA'),
(970, 'Unidad de Valor Real', 'COU'),
(971, 'Afghani', 'AFN'),
(972, 'Somoni', 'TJS'),
(973, 'Kwanza', 'AOA'),
(974, 'Rouble bélorusse', 'BYR'),
(975, 'Lev de Bulgarie', 'BGN'),
(976, 'Franc Congolais', 'CDF'),
(977, 'Mark convertible', 'BAM'),
(978, 'Euro', 'EUR'),
(979, 'Mexican Unidad de Inversion (UDI)', 'MXV'),
(980, 'Hryvnia', 'UAH'),
(981, 'Lari', 'GEL'),
(984, 'Mvdol', 'BOV'),
(985, 'Zloty', 'PLN'),
(986, 'Real de Brésil', 'BRL'),
(990, 'Unité d''investissement', 'CLF'),
(998, 'Dollar des États-Unis (Même jour)', 'USN');

